laravel-basic1/routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\UserController;
use App\Http\Controllers\category_controller;
use App\Http\Controllers\item_controller;

// Route::get('users', [UserController::class, 'index'])->name('users.index');
Route::resource('/users', UserController::class);
Route::get('category', [category_controller::class, 'getDataCate']);
Route::get('item', [item_controller::class, 'getDataItem']);

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

laravel-basic1/app/Models/Category.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

/**
 * Models categories
 * @property int id
 * @property string name4
 * @package App\Models
 */

class Category extends Model
{
    use HasFactory;

    /**
     * Initialize fillable
     */
    protected $table = 'categories';
    protected $fillable = [
        'name',
        'description',
    ];

    // public function item() {
    //     return $this->hasMany(item::class);
    // }
}

laravel-basic1/app/Models/Item.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

/**
 * Models Item
 * @property int id
 * @property string name4
 * @package App\Models
 */

class Item extends Model
{
    use HasFactory;


    /**
     * Initialize fillable
     */
    protected $table = 'items';
    protected $fillable = [
        'name',
    ];

    // public function category() {
    //     return $this->belongsTo(categories::class);
    // }
}

laravel-basic1/app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;
use Hash;
use DB;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $table = "users";
    protected $fillable = [
        'mail_address',
        'password',
        'name',
        'address',
        'phone',
    ];  

    public function handle($request) {
        return User::create([
            'mail_address' => $request ->mail_address,
            'password' => Hash::make($request ->password),
            'name' => $request ->name,
            'address' => $request ->address,
            'phone' => $request ->phone,
        ]);
    }
}

laravel-basic1/app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use App\Models\Category;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;

    public function index() {
        // //collection of model instance
        // $allCategories = Category::all();

        // //array of fied data
        // $allCategoriesTransformed = $allCategories->toArray();

        // //Query builder
        // $queryBuilder = Category::query()->where('id', '>', 2)->orderByDesc('id');

        // //Execute query builder
        // $result = $queryBuilder->get();

        // dd($allCategories, $allCategoriesTransformed, $queryBuilder, $result);
        // return 'End turn';



        // $recentUpdated = Category::query()->recentUpdated()->get();

        // dd($recentUpdated);
        // return 'end turn';



        // $category = Category::first();
        // //collection of items model instance
        // $items = $category->items;
        // //Query buider of item in this category
        // $itemQueryBuilder = $category->items()->where('id', '>', 1);
        // //combined use of relation and local scope
        // $recentUpdateItems = Item::whereHas('category', function($q) {
        //     return $q->recentUpdated();
        // })
        // ->get();

        // dd($items, $itemQueryBuilder, $recentUpdateItems);
        // return 'End turn';



        // //collection of all Category
        // $categories = Category::all();

        // //create ann array with key by id and value is name
        // $plucked = $categories->pluck('name', 'id');

        // //collection filter
        // $filtered = $categories->filter(function($cat) {
        //     return $cat->id > 2;
        // });

        // //get only some field in type of Array
        // $only = $categories->only(['id', 'updated_at'])->toArray();
        // dd($plucked, $filtered, $only);
        // return 'End turn';


        //coleection of all category
        $categories = Category::all();
        //create an array with key by Id and value is name
        $plucked = $categories->pluck('name', 'id')->toArray();

        dd($plucked);
        return 'End turn';
    }
}

laravel-basic1/app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\User;
use App\Http\Requests\CreateUserRequest;
use DB;

class UserController extends Controller
{
    public function index() {

        // $user = User::orderBy('mail_address', 'asc')->paginate(20);
        $user = DB::table('users')
        ->orderBy('mail_address', 'asc')
        ->paginate(20);
        return view('user.index', compact('user'))->with('i', (request()->input('page',1) -1) *20);
    }
    

    /**
     * Show the form to create a new blog users.
     *
     * @return \Illuminate\View\View
     */
    public function create()
    {
        return view('user.create');
    }
 
    /**
     * Store a new blog post.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateUserRequest $request)
    {

        $validated = $request->validated();

        if (User::handle($request)) {
            session()->flash('message', 'Thêm thành công');
            return redirect()->route('users.index');
        }
    }
}

laravel-basic1/app/Http/Controllers/category_controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\categories;

class category_controller extends Controller
{
    function getDataCate() {
        return categories::all();
    }
    //
}

laravel-basic1/app/Http/Controllers/item_controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Models\item;

class item_controller extends Controller
{
    function getDataItem() {
        return item::all();
    }
    //
}

laravel-basic1/resources/views/user/create.blade.php
@extends('user.list')

@section('content')
    <div class="container" style = "margin-top: 15px;">
        <div class="card">
            <div class="card-header">
                <div class="row">
                    <div class="col-md-6">
                        <h3>Thêm mới</h3>
                    </div>
                    <div class="col-md-6">
                        <a href="{{ route('users.index') }}" class = "btn btn-primary float-end">Danh sách</a>
                    </div>
                </div>
            </div>
            <div class="card-body">
                <form action="{{ route('users.store') }}" method = "POST">
                    @csrf
                    <div class="row">
                        <div class="col-md-6" style = "margin-left: 300px;">
                            <div class="form-group">
                                <strong style = " @error('mail_address') color:red; @enderror">Mail_address</strong>
                                <input type="text" name = "mail_address" style = " @error('mail_address') border:red solid; @enderror" value = "{{ old('mail_address') }}" class = "form-control" placeholder="Nhap mail">
                                @error('mail_address')
                                    <div class="white text-danger" style = "color:red;">{{ $message }}</div>
                                 @enderror
                            </div>

                            <div class="form-group">
                                <strong style = " @error('password') color:red; @enderror">Password</strong>
                                <input type="password" name = "password" style = " @error('password') border:red solid; @enderror" class = "form-control" placeholder="Nhap password">
                                @error('password')
                                    <div class="white text-danger" style = "color:red;">{{ $message }}</div>
                                 @enderror
                            </div>

                            <div class="form-group">
                                <strong style = " @error('password_confirm') color:red; @enderror">Password_confirm</strong>
                                <input type="password" name = "password_confirm" style = " @error('password_confirm') border:red solid; @enderror" class = "form-control" placeholder="Nhap password_confirm">
                                @error('password_confirm')
                                    <div class="white text-danger" style = "color:red;">{{ $message }}</div>
                                 @enderror
                            </div>

                            <div class="form-group">
                                <strong style = " @error('name') color:red; @enderror">Name</strong>
                                <input type="text" name = "name" style = " @error('name') border:red solid; @enderror" value = "{{ old('name') }}" class = "form-control" placeholder="Nhap name">
                                @error('name')
                                    <div class="white text-danger" style = "color:red;">{{ $message }}</div>
                                 @enderror
                            </div>

                            <div class="form-group">
                                <strong style = " @error('address') color:red; @enderror">Address</strong>
                                <input type="text" name = "address" style = " @error('address') border:red solid; @enderror" value = "{{ old('address') }}" class = "form-control" placeholder="Nhap address">
                                @error('address')
                                    <div class="white text-danger" style = "color:red;">{{ $message }}</div>
                                 @enderror
                            </div>

                            <div class="form-group">
                                <strong style = " @error('phone') color:red; @enderror">Phone</strong>
                                <input type="text" name = "phone" style = " @error('phone') border:red solid; @enderror" value = "{{ old('phone') }}" class = "form-control" placeholder="Nhap phone">
                                @error('phone')
                                    <div class="white text-danger" style = "color:red;">{{ $message }}</div>
                                 @enderror
                            </div>

                            <button type="submit" name="submit" class="btn btn-primary" style = "margin-top: 20px;">Submit</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
    
@endsection

laravel-basic1/resources/views/user/index.blade.php
@extends('user.list')

@section('content')
    <div class="container" style = "margin-top: 15px;">
        <div class="card">
            <div class="card-header">
                <div class="row">
                    <div class="col-md-6">
                        <h3>Laravel basic 2</h3>
                    </div>
                    <div class="col-md-6">
                        <a href="{{ route('users.create') }}" class = "btn btn-primary float-end" style = "margin-top: 20px;">Thêm mới</a>
                    </div>
                    <div class="col-md-6">
                        <h5 style = "color:rgb(65, 125, 236)">Danh sách</h5>
                    </div>
                </div>
            </div>
            <div class="card-body">
                <table class="table table-striped">
                    <div>
                        @if (session()->has('message'))
                            <div class="alert alert-success">
                                {{ session('message') }}
                            </div>
                        @endif
                    </div>
                    <thead>
                        <tr>
                            <th style = "text-align: center;">STT</th>
                            <th style = "text-align: center;">Mail_address</th>
                            <th style = "text-align: center;">Password</th>
                            <th style = "text-align: center;">Name</th>
                            <th style = "text-align: center;">Address</th>
                            <th style = "text-align: center;">Phone</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($user as $us)
                        <tr>
                            <td>{{ ++$i }}</td>
                            <td>{{ $us->mail_address }}</td>
                            <td>{{ $us->password }}</td>
                            <td>{{ $us->name }}</td>
                            <td>{{ $us->address }}</td>
                            <td>{{ $us->phone }}</td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
            {{ $user->links() }}
        </div>
    </div>

@endsection

laravel-basic1/resources/views/user/list.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.1/dist/css/bootstrap.min.css" rel="stylesheet">
    <title>Laravel Basic 2</title>
</head>
<body>
    @yield('content')

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</body>
</html>